#!/usr/bin/env bash
echo 'Test encrypting and decrypting with armored key... success.' |
./bin/sop-openpgp encrypt test/testkey.asc |
./bin/sop-openpgp decrypt test/testkey.sec.asc || exit

echo 'Test encrypting and decrypting with binary key... success.' |
./bin/sop-openpgp encrypt test/testkey.pgp |
./bin/sop-openpgp decrypt test/testkey.sec.pgp || exit

echo 'Test encrypting and decrypting with password' |
./bin/sop-openpgp encrypt --with-password=123 |
./bin/sop-openpgp decrypt --with-password=123 || exit

echo 'Test signing' |
./bin/sop-openpgp sign test/alice.sec || exit

echo 'test verifyng message signature'
./bin/sop-openpgp verify test/detached-sig.txt test/alice.asc < test/message.txt || exit

echo 'test generating key'
./bin/sop-openpgp generate-key 'alice <alice@alice.ch>' || exit
